"""
ValUprop.in — Locality Price Database
locality_db.py

Rebuilt Jun 2026 from chennai_cma_locality_seed.csv (165 localities)
+ curated rich entries for key markets
+ Bangalore (unchanged)
"""

from dataclasses import dataclass, field
from typing import Optional

@dataclass
class LocalityData:
    city:              str
    locality:          str
    land_rate_lo:      float
    land_rate_hi:      float
    apt_rate_lo:       float
    apt_rate_hi:       float
    guideline_value:   float
    trend_12m:         str
    micro_context:     str
    infra_notes:       str
    data_confidence:   int          = 75
    demand_drivers:    list         = field(default_factory=list)
    risk_factors:      list         = field(default_factory=list)

LOCALITY_DB: dict[str, LocalityData] = {

    # ── Chennai (from CSV seed + curated) ───────────────────────────

    "Chennai|Tiruvottiyur": LocalityData(
        city="Chennai", locality="Tiruvottiyur",
        land_rate_lo=5500, land_rate_hi=9000,
        apt_rate_lo=6000,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Tiruvottiyur is a residential locality in Chennai, Zone 1 - Thiruvottiyur.",
        infra_notes="Pincode 600019. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kaladipet": LocalityData(
        city="Chennai", locality="Kaladipet",
        land_rate_lo=5200, land_rate_hi=8200,
        apt_rate_lo=5800,  apt_rate_hi=8800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kaladipet is a residential locality in Chennai, Zone 1 - Thiruvottiyur.",
        infra_notes="Pincode 600019. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ennore": LocalityData(
        city="Chennai", locality="Ennore",
        land_rate_lo=4000, land_rate_hi=6500,
        apt_rate_lo=4500,  apt_rate_hi=7000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Ennore is a residential locality in Chennai, Zone 1 - Thiruvottiyur.",
        infra_notes="Pincode 600057. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Wimco Nagar": LocalityData(
        city="Chennai", locality="Wimco Nagar",
        land_rate_lo=4200, land_rate_hi=6800,
        apt_rate_lo=4800,  apt_rate_hi=7200,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Wimco Nagar is a residential locality in Chennai, Zone 1 - Thiruvottiyur.",
        infra_notes="Pincode 600057. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kathivakkam": LocalityData(
        city="Chennai", locality="Kathivakkam",
        land_rate_lo=3800, land_rate_hi=6200,
        apt_rate_lo=4200,  apt_rate_hi=6500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kathivakkam is a residential locality in Chennai, Zone 1 - Thiruvottiyur.",
        infra_notes="Pincode 600060. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Manali": LocalityData(
        city="Chennai", locality="Manali",
        land_rate_lo=3800, land_rate_hi=6500,
        apt_rate_lo=4200,  apt_rate_hi=6800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Manali is a residential locality in Chennai, Zone 2 - Manali.",
        infra_notes="Pincode 600068. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Manali New Town": LocalityData(
        city="Chennai", locality="Manali New Town",
        land_rate_lo=3500, land_rate_hi=6000,
        apt_rate_lo=4000,  apt_rate_hi=6500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Manali New Town is a residential locality in Chennai, Zone 2 - Manali.",
        infra_notes="Pincode 600103. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mathur": LocalityData(
        city="Chennai", locality="Mathur",
        land_rate_lo=3500, land_rate_hi=5800,
        apt_rate_lo=4000,  apt_rate_hi=6200,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Mathur is a residential locality in Chennai, Zone 2 - Manali.",
        infra_notes="Pincode 600068. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sathangadu": LocalityData(
        city="Chennai", locality="Sathangadu",
        land_rate_lo=3200, land_rate_hi=5500,
        apt_rate_lo=3800,  apt_rate_hi=6000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Sathangadu is a residential locality in Chennai, Zone 2 - Manali.",
        infra_notes="Pincode 600019. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Madhavaram": LocalityData(
        city="Chennai", locality="Madhavaram",
        land_rate_lo=5000, land_rate_hi=8200,
        apt_rate_lo=5500,  apt_rate_hi=8500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Madhavaram is a residential locality in Chennai, Zone 3 - Madhavaram.",
        infra_notes="Pincode 600060. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Madhavaram Milk Colony": LocalityData(
        city="Chennai", locality="Madhavaram Milk Colony",
        land_rate_lo=5200, land_rate_hi=8500,
        apt_rate_lo=5800,  apt_rate_hi=8800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Madhavaram Milk Colony is a residential locality in Chennai, Zone 3 - Madhavaram.",
        infra_notes="Pincode 600051. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Puzhal": LocalityData(
        city="Chennai", locality="Puzhal",
        land_rate_lo=3500, land_rate_hi=5500,
        apt_rate_lo=3800,  apt_rate_hi=5800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Puzhal is a residential locality in Chennai, Zone 3 - Madhavaram.",
        infra_notes="Pincode 600066. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kodungaiyur": LocalityData(
        city="Chennai", locality="Kodungaiyur",
        land_rate_lo=4500, land_rate_hi=7500,
        apt_rate_lo=5000,  apt_rate_hi=7800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kodungaiyur is a residential locality in Chennai, Zone 3 - Madhavaram.",
        infra_notes="Pincode 600118. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Surapet": LocalityData(
        city="Chennai", locality="Surapet",
        land_rate_lo=4000, land_rate_hi=6800,
        apt_rate_lo=4500,  apt_rate_hi=7000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Surapet is a residential locality in Chennai, Zone 3 - Madhavaram.",
        infra_notes="Pincode 600066. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Tondiarpet": LocalityData(
        city="Chennai", locality="Tondiarpet",
        land_rate_lo=6500, land_rate_hi=11000,
        apt_rate_lo=7000,  apt_rate_hi=11500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Tondiarpet is a residential locality in Chennai, Zone 4 - Tondiarpet.",
        infra_notes="Pincode 600081. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Old Washermanpet": LocalityData(
        city="Chennai", locality="Old Washermanpet",
        land_rate_lo=5800, land_rate_hi=9200,
        apt_rate_lo=6000,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Old Washermanpet is a residential locality in Chennai, Zone 4 - Tondiarpet.",
        infra_notes="Pincode 600021. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Korukkupet": LocalityData(
        city="Chennai", locality="Korukkupet",
        land_rate_lo=5500, land_rate_hi=8800,
        apt_rate_lo=5800,  apt_rate_hi=9000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Korukkupet is a residential locality in Chennai, Zone 4 - Tondiarpet.",
        infra_notes="Pincode 600021. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Vyasarpadi": LocalityData(
        city="Chennai", locality="Vyasarpadi",
        land_rate_lo=4500, land_rate_hi=7500,
        apt_rate_lo=5000,  apt_rate_hi=7800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Vyasarpadi is a residential locality in Chennai, Zone 4 - Tondiarpet.",
        infra_notes="Pincode 600039. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Tollgate": LocalityData(
        city="Chennai", locality="Tollgate",
        land_rate_lo=5500, land_rate_hi=9000,
        apt_rate_lo=6000,  apt_rate_hi=9200,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Tollgate is a residential locality in Chennai, Zone 4 - Tondiarpet.",
        infra_notes="Pincode 600021. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Royapuram": LocalityData(
        city="Chennai", locality="Royapuram",
        land_rate_lo=9500, land_rate_hi=16000,
        apt_rate_lo=10000,  apt_rate_hi=16500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Royapuram is a residential locality in Chennai, Zone 5 - Royapuram.",
        infra_notes="Pincode 600013. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mannady": LocalityData(
        city="Chennai", locality="Mannady",
        land_rate_lo=9000, land_rate_hi=15500,
        apt_rate_lo=9000,  apt_rate_hi=15000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Mannady is a residential locality in Chennai, Zone 5 - Royapuram.",
        infra_notes="Pincode 600001. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Parrys": LocalityData(
        city="Chennai", locality="Parrys",
        land_rate_lo=8500, land_rate_hi=15000,
        apt_rate_lo=8500,  apt_rate_hi=14500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Parrys is a residential locality in Chennai, Zone 5 - Royapuram.",
        infra_notes="Pincode 600001. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sowcarpet": LocalityData(
        city="Chennai", locality="Sowcarpet",
        land_rate_lo=10000, land_rate_hi=17500,
        apt_rate_lo=9500,  apt_rate_hi=16500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Sowcarpet is a residential locality in Chennai, Zone 5 - Royapuram.",
        infra_notes="Pincode 600079. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Washermanpet": LocalityData(
        city="Chennai", locality="Washermanpet",
        land_rate_lo=6000, land_rate_hi=10000,
        apt_rate_lo=6500,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Washermanpet is a residential locality in Chennai, Zone 5 - Royapuram.",
        infra_notes="Pincode 600021. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Perambur": LocalityData(
        city="Chennai", locality="Perambur",
        land_rate_lo=6000, land_rate_hi=9500,
        apt_rate_lo=6500,  apt_rate_hi=10000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Perambur is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600011. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ayanavaram": LocalityData(
        city="Chennai", locality="Ayanavaram",
        land_rate_lo=7000, land_rate_hi=11000,
        apt_rate_lo=7000,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Ayanavaram is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600023. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Pulianthope": LocalityData(
        city="Chennai", locality="Pulianthope",
        land_rate_lo=5200, land_rate_hi=8200,
        apt_rate_lo=5500,  apt_rate_hi=8500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Pulianthope is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600012. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Otteri": LocalityData(
        city="Chennai", locality="Otteri",
        land_rate_lo=6500, land_rate_hi=10500,
        apt_rate_lo=6500,  apt_rate_hi=10000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Otteri is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600012. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kosapet": LocalityData(
        city="Chennai", locality="Kosapet",
        land_rate_lo=6200, land_rate_hi=10000,
        apt_rate_lo=6500,  apt_rate_hi=10000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kosapet is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600012. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Choolai": LocalityData(
        city="Chennai", locality="Choolai",
        land_rate_lo=6500, land_rate_hi=10500,
        apt_rate_lo=6800,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Choolai is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600112. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sembium": LocalityData(
        city="Chennai", locality="Sembium",
        land_rate_lo=5800, land_rate_hi=9200,
        apt_rate_lo=6000,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Sembium is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600011. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Erukkancherry": LocalityData(
        city="Chennai", locality="Erukkancherry",
        land_rate_lo=4500, land_rate_hi=7200,
        apt_rate_lo=4800,  apt_rate_hi=7500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Erukkancherry is a residential locality in Chennai, Zone 6 - Thiru Vi Ka Nagar.",
        infra_notes="Pincode 600118. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ambattur": LocalityData(
        city="Chennai", locality="Ambattur",
        land_rate_lo=4800, land_rate_hi=7200,
        apt_rate_lo=5000,  apt_rate_hi=7500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Ambattur is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600053. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Korattur": LocalityData(
        city="Chennai", locality="Korattur",
        land_rate_lo=6000, land_rate_hi=9000,
        apt_rate_lo=6500,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Korattur is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600080. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mogappair": LocalityData(
        city="Chennai", locality="Mogappair",
        land_rate_lo=7000, land_rate_hi=11000,
        apt_rate_lo=7500,  apt_rate_hi=11000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Mogappair is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600037. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mogappair West": LocalityData(
        city="Chennai", locality="Mogappair West",
        land_rate_lo=6800, land_rate_hi=10500,
        apt_rate_lo=7000,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Mogappair West is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600037. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Nolambur": LocalityData(
        city="Chennai", locality="Nolambur",
        land_rate_lo=6500, land_rate_hi=9800,
        apt_rate_lo=7000,  apt_rate_hi=10000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Nolambur is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600095. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Padi": LocalityData(
        city="Chennai", locality="Padi",
        land_rate_lo=5500, land_rate_hi=8800,
        apt_rate_lo=6000,  apt_rate_hi=9000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Padi is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600050. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Anna Nagar West Extn": LocalityData(
        city="Chennai", locality="Anna Nagar West Extn",
        land_rate_lo=8000, land_rate_hi=13000,
        apt_rate_lo=8500,  apt_rate_hi=13000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Anna Nagar West Extn is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600101. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ayappakkam": LocalityData(
        city="Chennai", locality="Ayappakkam",
        land_rate_lo=4200, land_rate_hi=6800,
        apt_rate_lo=4500,  apt_rate_hi=7000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Ayappakkam is a residential locality in Chennai, Zone 7 - Ambattur.",
        infra_notes="Pincode 600077. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Anna Nagar": LocalityData(
        city="Chennai", locality="Anna Nagar",
        land_rate_lo=13000, land_rate_hi=21000,
        apt_rate_lo=12000,  apt_rate_hi=18000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Anna Nagar is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600040. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Anna Nagar West": LocalityData(
        city="Chennai", locality="Anna Nagar West",
        land_rate_lo=11000, land_rate_hi=17000,
        apt_rate_lo=10000,  apt_rate_hi=14500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Anna Nagar West is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600101. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Shenoy Nagar": LocalityData(
        city="Chennai", locality="Shenoy Nagar",
        land_rate_lo=11000, land_rate_hi=16000,
        apt_rate_lo=10000,  apt_rate_hi=14500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Shenoy Nagar is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600030. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Aminjikarai": LocalityData(
        city="Chennai", locality="Aminjikarai",
        land_rate_lo=9000, land_rate_hi=14000,
        apt_rate_lo=8500,  apt_rate_hi=12500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Aminjikarai is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600029. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Villivakkam": LocalityData(
        city="Chennai", locality="Villivakkam",
        land_rate_lo=8000, land_rate_hi=13000,
        apt_rate_lo=7000,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Villivakkam is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600049. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kolathur": LocalityData(
        city="Chennai", locality="Kolathur",
        land_rate_lo=5000, land_rate_hi=7800,
        apt_rate_lo=5500,  apt_rate_hi=8000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kolathur is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600099. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Purasawalkam": LocalityData(
        city="Chennai", locality="Purasawalkam",
        land_rate_lo=12000, land_rate_hi=19000,
        apt_rate_lo=11000,  apt_rate_hi=17500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Purasawalkam is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600084. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Vepery": LocalityData(
        city="Chennai", locality="Vepery",
        land_rate_lo=10000, land_rate_hi=17000,
        apt_rate_lo=10000,  apt_rate_hi=16000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Vepery is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600007. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Periyar Nagar": LocalityData(
        city="Chennai", locality="Periyar Nagar",
        land_rate_lo=6500, land_rate_hi=10500,
        apt_rate_lo=6500,  apt_rate_hi=10000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Periyar Nagar is a residential locality in Chennai, Zone 8 - Anna Nagar.",
        infra_notes="Pincode 600082. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Teynampet": LocalityData(
        city="Chennai", locality="Teynampet",
        land_rate_lo=17000, land_rate_hi=28000,
        apt_rate_lo=15000,  apt_rate_hi=23000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Teynampet is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600018. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Alwarpet": LocalityData(
        city="Chennai", locality="Alwarpet",
        land_rate_lo=20000, land_rate_hi=35000,
        apt_rate_lo=18000,  apt_rate_hi=26000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Alwarpet is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600018. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Nungambakkam": LocalityData(
        city="Chennai", locality="Nungambakkam",
        land_rate_lo=18000, land_rate_hi=30000,
        apt_rate_lo=15000,  apt_rate_hi=22000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Nungambakkam is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600034. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|T Nagar": LocalityData(
        city="Chennai", locality="T Nagar",
        land_rate_lo=18000, land_rate_hi=28000,
        apt_rate_lo=16000,  apt_rate_hi=21000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="T Nagar is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600017. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Chetpet": LocalityData(
        city="Chennai", locality="Chetpet",
        land_rate_lo=13000, land_rate_hi=20000,
        apt_rate_lo=12000,  apt_rate_hi=17500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Chetpet is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600031. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Gopalapuram": LocalityData(
        city="Chennai", locality="Gopalapuram",
        land_rate_lo=18000, land_rate_hi=30000,
        apt_rate_lo=16000,  apt_rate_hi=24000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Gopalapuram is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600086. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Egmore": LocalityData(
        city="Chennai", locality="Egmore",
        land_rate_lo=12000, land_rate_hi=19000,
        apt_rate_lo=11000,  apt_rate_hi=16500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Egmore is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600008. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Triplicane": LocalityData(
        city="Chennai", locality="Triplicane",
        land_rate_lo=8500, land_rate_hi=14500,
        apt_rate_lo=8000,  apt_rate_hi=13000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Triplicane is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600005. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Royapettah": LocalityData(
        city="Chennai", locality="Royapettah",
        land_rate_lo=12000, land_rate_hi=19000,
        apt_rate_lo=11000,  apt_rate_hi=16000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Royapettah is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600014. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thousand Lights": LocalityData(
        city="Chennai", locality="Thousand Lights",
        land_rate_lo=16000, land_rate_hi=26000,
        apt_rate_lo=14000,  apt_rate_hi=21000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Thousand Lights is a residential locality in Chennai, Zone 9 - Teynampet.",
        infra_notes="Pincode 600006. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kodambakkam": LocalityData(
        city="Chennai", locality="Kodambakkam",
        land_rate_lo=10000, land_rate_hi=16000,
        apt_rate_lo=9000,  apt_rate_hi=13500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kodambakkam is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600024. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Vadapalani": LocalityData(
        city="Chennai", locality="Vadapalani",
        land_rate_lo=10000, land_rate_hi=16000,
        apt_rate_lo=9500,  apt_rate_hi=14000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Vadapalani is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600026. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ashok Nagar": LocalityData(
        city="Chennai", locality="Ashok Nagar",
        land_rate_lo=11000, land_rate_hi=17000,
        apt_rate_lo=10000,  apt_rate_hi=14500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Ashok Nagar is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600083. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|KK Nagar": LocalityData(
        city="Chennai", locality="KK Nagar",
        land_rate_lo=10000, land_rate_hi=16000,
        apt_rate_lo=9000,  apt_rate_hi=13500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="KK Nagar is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600078. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Saligramam": LocalityData(
        city="Chennai", locality="Saligramam",
        land_rate_lo=9000, land_rate_hi=14000,
        apt_rate_lo=8500,  apt_rate_hi=13000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Saligramam is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600093. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Choolaimedu": LocalityData(
        city="Chennai", locality="Choolaimedu",
        land_rate_lo=8500, land_rate_hi=13500,
        apt_rate_lo=8000,  apt_rate_hi=11500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Choolaimedu is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600094. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Nesapakkam": LocalityData(
        city="Chennai", locality="Nesapakkam",
        land_rate_lo=8500, land_rate_hi=13500,
        apt_rate_lo=8000,  apt_rate_hi=11500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Nesapakkam is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600078. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|MGR Nagar": LocalityData(
        city="Chennai", locality="MGR Nagar",
        land_rate_lo=8000, land_rate_hi=13000,
        apt_rate_lo=7500,  apt_rate_hi=11000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="MGR Nagar is a residential locality in Chennai, Zone 10 - Kodambakkam.",
        infra_notes="Pincode 600078. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Valasaravakkam": LocalityData(
        city="Chennai", locality="Valasaravakkam",
        land_rate_lo=7000, land_rate_hi=11000,
        apt_rate_lo=7000,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Valasaravakkam is a residential locality in Chennai, Zone 11 - Valasaravakkam.",
        infra_notes="Pincode 600087. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Porur": LocalityData(
        city="Chennai", locality="Porur",
        land_rate_lo=7000, land_rate_hi=11500,
        apt_rate_lo=7500,  apt_rate_hi=11000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Porur is a residential locality in Chennai, Zone 11 - Valasaravakkam.",
        infra_notes="Pincode 600116. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ramapuram": LocalityData(
        city="Chennai", locality="Ramapuram",
        land_rate_lo=6800, land_rate_hi=10500,
        apt_rate_lo=7000,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Ramapuram is a residential locality in Chennai, Zone 11 - Valasaravakkam.",
        infra_notes="Pincode 600089. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Maduravoyal": LocalityData(
        city="Chennai", locality="Maduravoyal",
        land_rate_lo=6000, land_rate_hi=9500,
        apt_rate_lo=6500,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Maduravoyal is a residential locality in Chennai, Zone 11 - Valasaravakkam.",
        infra_notes="Pincode 600095. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Virugambakkam": LocalityData(
        city="Chennai", locality="Virugambakkam",
        land_rate_lo=8500, land_rate_hi=13500,
        apt_rate_lo=8000,  apt_rate_hi=12000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Virugambakkam is a residential locality in Chennai, Zone 11 - Valasaravakkam.",
        infra_notes="Pincode 600092. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Alwarthirunagar": LocalityData(
        city="Chennai", locality="Alwarthirunagar",
        land_rate_lo=7000, land_rate_hi=11000,
        apt_rate_lo=7000,  apt_rate_hi=10500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Alwarthirunagar is a residential locality in Chennai, Zone 11 - Valasaravakkam.",
        infra_notes="Pincode 600087. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Iyyappanthangal": LocalityData(
        city="Chennai", locality="Iyyappanthangal",
        land_rate_lo=5000, land_rate_hi=8000,
        apt_rate_lo=5500,  apt_rate_hi=8500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Iyyappanthangal is a residential locality in Chennai, Zone 11 - Valasaravakkam.",
        infra_notes="Pincode 600056. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Alandur": LocalityData(
        city="Chennai", locality="Alandur",
        land_rate_lo=9500, land_rate_hi=15500,
        apt_rate_lo=9000,  apt_rate_hi=13500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Alandur is a residential locality in Chennai, Zone 12 - Alandur.",
        infra_notes="Pincode 600016. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Nanganallur": LocalityData(
        city="Chennai", locality="Nanganallur",
        land_rate_lo=8000, land_rate_hi=13000,
        apt_rate_lo=8000,  apt_rate_hi=12000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Nanganallur is a residential locality in Chennai, Zone 12 - Alandur.",
        infra_notes="Pincode 600061. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Pazhavanthangal": LocalityData(
        city="Chennai", locality="Pazhavanthangal",
        land_rate_lo=8000, land_rate_hi=13000,
        apt_rate_lo=8000,  apt_rate_hi=12000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Pazhavanthangal is a residential locality in Chennai, Zone 12 - Alandur.",
        infra_notes="Pincode 600114. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|St Thomas Mount": LocalityData(
        city="Chennai", locality="St Thomas Mount",
        land_rate_lo=8500, land_rate_hi=13500,
        apt_rate_lo=8500,  apt_rate_hi=12500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="St Thomas Mount is a residential locality in Chennai, Zone 12 - Alandur.",
        infra_notes="Pincode 600016. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Meenambakkam": LocalityData(
        city="Chennai", locality="Meenambakkam",
        land_rate_lo=6500, land_rate_hi=10000,
        apt_rate_lo=6500,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Meenambakkam is a residential locality in Chennai, Zone 12 - Alandur.",
        infra_notes="Pincode 600027. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Adambakkam": LocalityData(
        city="Chennai", locality="Adambakkam",
        land_rate_lo=7500, land_rate_hi=12000,
        apt_rate_lo=7500,  apt_rate_hi=11000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Adambakkam is a residential locality in Chennai, Zone 12 - Alandur.",
        infra_notes="Pincode 600088. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Adyar": LocalityData(
        city="Chennai", locality="Adyar",
        land_rate_lo=15000, land_rate_hi=22000,
        apt_rate_lo=14500,  apt_rate_hi=19000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Adyar is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600020. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Besant Nagar": LocalityData(
        city="Chennai", locality="Besant Nagar",
        land_rate_lo=16000, land_rate_hi=23000,
        apt_rate_lo=14000,  apt_rate_hi=18500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Besant Nagar is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600090. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thiruvanmiyur": LocalityData(
        city="Chennai", locality="Thiruvanmiyur",
        land_rate_lo=12000, land_rate_hi=18000,
        apt_rate_lo=12000,  apt_rate_hi=16500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Thiruvanmiyur is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600041. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kottivakkam": LocalityData(
        city="Chennai", locality="Kottivakkam",
        land_rate_lo=12000, land_rate_hi=19000,
        apt_rate_lo=11000,  apt_rate_hi=15500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kottivakkam is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600041. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Palavakkam": LocalityData(
        city="Chennai", locality="Palavakkam",
        land_rate_lo=13000, land_rate_hi=20000,
        apt_rate_lo=11000,  apt_rate_hi=16000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Palavakkam is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600041. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Neelankarai": LocalityData(
        city="Chennai", locality="Neelankarai",
        land_rate_lo=12000, land_rate_hi=22000,
        apt_rate_lo=10000,  apt_rate_hi=15500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Neelankarai is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600115. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Injambakkam": LocalityData(
        city="Chennai", locality="Injambakkam",
        land_rate_lo=10000, land_rate_hi=18000,
        apt_rate_lo=9500,  apt_rate_hi=14000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Injambakkam is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600115. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Velachery": LocalityData(
        city="Chennai", locality="Velachery",
        land_rate_lo=8000, land_rate_hi=12000,
        apt_rate_lo=7850,  apt_rate_hi=13250,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Velachery is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600042. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Guindy": LocalityData(
        city="Chennai", locality="Guindy",
        land_rate_lo=9000, land_rate_hi=14000,
        apt_rate_lo=9000,  apt_rate_hi=13500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Guindy is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600032. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kotturpuram": LocalityData(
        city="Chennai", locality="Kotturpuram",
        land_rate_lo=13000, land_rate_hi=20000,
        apt_rate_lo=12000,  apt_rate_hi=17500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kotturpuram is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600085. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Saidapet": LocalityData(
        city="Chennai", locality="Saidapet",
        land_rate_lo=9000, land_rate_hi=14000,
        apt_rate_lo=8000,  apt_rate_hi=12500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Saidapet is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600015. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Akkarai": LocalityData(
        city="Chennai", locality="Akkarai",
        land_rate_lo=11000, land_rate_hi=19000,
        apt_rate_lo=9500,  apt_rate_hi=14000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Akkarai is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600119. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Uthandi": LocalityData(
        city="Chennai", locality="Uthandi",
        land_rate_lo=8000, land_rate_hi=15000,
        apt_rate_lo=8000,  apt_rate_hi=12500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Uthandi is a residential locality in Chennai, Zone 13 - Adyar.",
        infra_notes="Pincode 600119. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Perungudi": LocalityData(
        city="Chennai", locality="Perungudi",
        land_rate_lo=6500, land_rate_hi=8500,
        apt_rate_lo=13500,  apt_rate_hi=18000,
        guideline_value=4400,
        trend_12m="+5.5%",
        micro_context="Perungudi is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600096. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thoraipakkam": LocalityData(
        city="Chennai", locality="Thoraipakkam",
        land_rate_lo=6000, land_rate_hi=7800,
        apt_rate_lo=11000,  apt_rate_hi=15500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Thoraipakkam is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600097. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Karapakkam": LocalityData(
        city="Chennai", locality="Karapakkam",
        land_rate_lo=6000, land_rate_hi=8200,
        apt_rate_lo=9500,  apt_rate_hi=13000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Karapakkam is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600097. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Pallikaranai": LocalityData(
        city="Chennai", locality="Pallikaranai",
        land_rate_lo=5500, land_rate_hi=7800,
        apt_rate_lo=6500,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Pallikaranai is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600100. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Madipakkam": LocalityData(
        city="Chennai", locality="Madipakkam",
        land_rate_lo=5500, land_rate_hi=7800,
        apt_rate_lo=6000,  apt_rate_hi=8800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Madipakkam is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600091. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Medavakkam": LocalityData(
        city="Chennai", locality="Medavakkam",
        land_rate_lo=4500, land_rate_hi=6800,
        apt_rate_lo=5500,  apt_rate_hi=8200,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Medavakkam is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600100. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Keelkattalai": LocalityData(
        city="Chennai", locality="Keelkattalai",
        land_rate_lo=4800, land_rate_hi=6800,
        apt_rate_lo=5800,  apt_rate_hi=8000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Keelkattalai is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600117. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kovilambakkam": LocalityData(
        city="Chennai", locality="Kovilambakkam",
        land_rate_lo=4500, land_rate_hi=6500,
        apt_rate_lo=5500,  apt_rate_hi=7800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Kovilambakkam is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600129. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Taramani": LocalityData(
        city="Chennai", locality="Taramani",
        land_rate_lo=7000, land_rate_hi=10000,
        apt_rate_lo=10000,  apt_rate_hi=15000,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Taramani is a residential locality in Chennai, Zone 14 - Perungudi.",
        infra_notes="Pincode 600113. GCC zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sholinganallur": LocalityData(
        city="Chennai", locality="Sholinganallur",
        land_rate_lo=5800, land_rate_hi=7800,
        apt_rate_lo=8500,  apt_rate_hi=12500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Sholinganallur is a residential locality in Chennai, Zone 15 - Sholinganallur.",
        infra_notes="Pincode 600119. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Perumbakkam": LocalityData(
        city="Chennai", locality="Perumbakkam",
        land_rate_lo=5500, land_rate_hi=7500,
        apt_rate_lo=6500,  apt_rate_hi=9200,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Perumbakkam is a residential locality in Chennai, Zone 15 - Sholinganallur.",
        infra_notes="Pincode 600100. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Semmancheri": LocalityData(
        city="Chennai", locality="Semmancheri",
        land_rate_lo=4000, land_rate_hi=5800,
        apt_rate_lo=5500,  apt_rate_hi=7800,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Semmancheri is a residential locality in Chennai, Zone 15 - Sholinganallur.",
        infra_notes="Pincode 600119. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Navalur": LocalityData(
        city="Chennai", locality="Navalur",
        land_rate_lo=6000, land_rate_hi=8500,
        apt_rate_lo=6800,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Navalur is a residential locality in Chennai, Zone 15 - Sholinganallur.",
        infra_notes="Pincode 600130. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Siruseri": LocalityData(
        city="Chennai", locality="Siruseri",
        land_rate_lo=4200, land_rate_hi=6000,
        apt_rate_lo=6000,  apt_rate_hi=8500,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Siruseri is a residential locality in Chennai, Zone 15 - Sholinganallur.",
        infra_notes="Pincode 603103. GCC zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sithalapakkam": LocalityData(
        city="Chennai", locality="Sithalapakkam",
        land_rate_lo=4000, land_rate_hi=5800,
        apt_rate_lo=5000,  apt_rate_hi=7200,
        guideline_value=0,
        trend_12m="+5.5%",
        micro_context="Sithalapakkam is a residential locality in Chennai, Zone 15 - Sholinganallur.",
        infra_notes="Pincode 600126. GCC zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Avadi": LocalityData(
        city="Chennai", locality="Avadi",
        land_rate_lo=3800, land_rate_hi=6000,
        apt_rate_lo=4000,  apt_rate_hi=6200,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Avadi is a residential locality in Chennai, Avadi Corporation.",
        infra_notes="Pincode 600054. Avadi Corp zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Pattabiram": LocalityData(
        city="Chennai", locality="Pattabiram",
        land_rate_lo=3500, land_rate_hi=5600,
        apt_rate_lo=3800,  apt_rate_hi=5800,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Pattabiram is a residential locality in Chennai, Avadi Corporation.",
        infra_notes="Pincode 600072. Avadi Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thirumullaivoyal": LocalityData(
        city="Chennai", locality="Thirumullaivoyal",
        land_rate_lo=4500, land_rate_hi=6500,
        apt_rate_lo=4450,  apt_rate_hi=6250,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Thirumullaivoyal is a residential locality in Chennai, Avadi Corporation.",
        infra_notes="Pincode 600062. Avadi Corp zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ambattur OT": LocalityData(
        city="Chennai", locality="Ambattur OT",
        land_rate_lo=4200, land_rate_hi=6800,
        apt_rate_lo=4500,  apt_rate_hi=7000,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Ambattur OT is a residential locality in Chennai, Avadi Corporation.",
        infra_notes="Pincode 600053. Avadi Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Paruthipattu": LocalityData(
        city="Chennai", locality="Paruthipattu",
        land_rate_lo=3600, land_rate_hi=5800,
        apt_rate_lo=4000,  apt_rate_hi=6000,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Paruthipattu is a residential locality in Chennai, Avadi Corporation.",
        infra_notes="Pincode 600071. Avadi Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kamaraj Nagar Avadi": LocalityData(
        city="Chennai", locality="Kamaraj Nagar Avadi",
        land_rate_lo=3600, land_rate_hi=5800,
        apt_rate_lo=4000,  apt_rate_hi=6000,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Kamaraj Nagar Avadi is a residential locality in Chennai, Avadi Corporation.",
        infra_notes="Pincode 600071. Avadi Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Tambaram": LocalityData(
        city="Chennai", locality="Tambaram",
        land_rate_lo=4500, land_rate_hi=7800,
        apt_rate_lo=5000,  apt_rate_hi=8000,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Tambaram is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600045. Tambaram Corp zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Tambaram West": LocalityData(
        city="Chennai", locality="Tambaram West",
        land_rate_lo=4200, land_rate_hi=7000,
        apt_rate_lo=4800,  apt_rate_hi=7200,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Tambaram West is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600045. Tambaram Corp zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|East Tambaram": LocalityData(
        city="Chennai", locality="East Tambaram",
        land_rate_lo=4200, land_rate_hi=7000,
        apt_rate_lo=4800,  apt_rate_hi=7200,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="East Tambaram is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600059. Tambaram Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Selaiyur": LocalityData(
        city="Chennai", locality="Selaiyur",
        land_rate_lo=4500, land_rate_hi=7200,
        apt_rate_lo=5000,  apt_rate_hi=7500,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Selaiyur is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600073. Tambaram Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Chromepet": LocalityData(
        city="Chennai", locality="Chromepet",
        land_rate_lo=5800, land_rate_hi=9000,
        apt_rate_lo=6000,  apt_rate_hi=9000,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Chromepet is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600044. Tambaram Corp zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Pallavaram": LocalityData(
        city="Chennai", locality="Pallavaram",
        land_rate_lo=6000, land_rate_hi=10000,
        apt_rate_lo=6000,  apt_rate_hi=9500,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Pallavaram is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600043. Tambaram Corp zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Pammal": LocalityData(
        city="Chennai", locality="Pammal",
        land_rate_lo=4800, land_rate_hi=7500,
        apt_rate_lo=5000,  apt_rate_hi=7500,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Pammal is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600075. Tambaram Corp zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Anakaputhur": LocalityData(
        city="Chennai", locality="Anakaputhur",
        land_rate_lo=4200, land_rate_hi=6800,
        apt_rate_lo=4500,  apt_rate_hi=7000,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Anakaputhur is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600070. Tambaram Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sembakkam": LocalityData(
        city="Chennai", locality="Sembakkam",
        land_rate_lo=4500, land_rate_hi=7200,
        apt_rate_lo=5000,  apt_rate_hi=7500,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Sembakkam is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600073. Tambaram Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Perungalathur": LocalityData(
        city="Chennai", locality="Perungalathur",
        land_rate_lo=3800, land_rate_hi=6000,
        apt_rate_lo=4200,  apt_rate_hi=6200,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Perungalathur is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600063. Tambaram Corp zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mudichur": LocalityData(
        city="Chennai", locality="Mudichur",
        land_rate_lo=3800, land_rate_hi=6000,
        apt_rate_lo=4200,  apt_rate_hi=6200,
        guideline_value=0,
        trend_12m="+7.5%",
        micro_context="Mudichur is a residential locality in Chennai, Tambaram Corporation.",
        infra_notes="Pincode 600048. Tambaram Corp zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Poonamallee": LocalityData(
        city="Chennai", locality="Poonamallee",
        land_rate_lo=4500, land_rate_hi=7000,
        apt_rate_lo=4500,  apt_rate_hi=6800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Poonamallee is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 600056. CMA zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thirumazhisai": LocalityData(
        city="Chennai", locality="Thirumazhisai",
        land_rate_lo=3200, land_rate_hi=5200,
        apt_rate_lo=3800,  apt_rate_hi=5800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Thirumazhisai is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 600124. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thiruverkadu": LocalityData(
        city="Chennai", locality="Thiruverkadu",
        land_rate_lo=4000, land_rate_hi=6200,
        apt_rate_lo=4500,  apt_rate_hi=6800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Thiruverkadu is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 600077. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thiruninravur": LocalityData(
        city="Chennai", locality="Thiruninravur",
        land_rate_lo=1800, land_rate_hi=3000,
        apt_rate_lo=2000,  apt_rate_hi=3000,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Thiruninravur is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 602024. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Veppampattu": LocalityData(
        city="Chennai", locality="Veppampattu",
        land_rate_lo=1600, land_rate_hi=2800,
        apt_rate_lo=1800,  apt_rate_hi=2900,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Veppampattu is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 602024. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Tiruvallur Town": LocalityData(
        city="Chennai", locality="Tiruvallur Town",
        land_rate_lo=550, land_rate_hi=2350,
        apt_rate_lo=2200,  apt_rate_hi=3800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Tiruvallur Town is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 602001. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ponneri": LocalityData(
        city="Chennai", locality="Ponneri",
        land_rate_lo=600, land_rate_hi=1800,
        apt_rate_lo=1800,  apt_rate_hi=3000,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Ponneri is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 601204. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Gummidipoondi": LocalityData(
        city="Chennai", locality="Gummidipoondi",
        land_rate_lo=350, land_rate_hi=1500,
        apt_rate_lo=1800,  apt_rate_hi=3200,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Gummidipoondi is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 601201. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Periyapalayam": LocalityData(
        city="Chennai", locality="Periyapalayam",
        land_rate_lo=350, land_rate_hi=1400,
        apt_rate_lo=1600,  apt_rate_hi=2800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Periyapalayam is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 601102. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sevvapet": LocalityData(
        city="Chennai", locality="Sevvapet",
        land_rate_lo=400, land_rate_hi=1400,
        apt_rate_lo=1500,  apt_rate_hi=2600,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Sevvapet is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 602025. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Uthukottai": LocalityData(
        city="Chennai", locality="Uthukottai",
        land_rate_lo=300, land_rate_hi=1300,
        apt_rate_lo=1400,  apt_rate_hi=2500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Uthukottai is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 602026. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Minjur": LocalityData(
        city="Chennai", locality="Minjur",
        land_rate_lo=900, land_rate_hi=2400,
        apt_rate_lo=2200,  apt_rate_hi=3800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Minjur is a residential locality in Chennai, CMA - Tiruvallur.",
        infra_notes="Pincode 601203. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Sriperumbudur": LocalityData(
        city="Chennai", locality="Sriperumbudur",
        land_rate_lo=3000, land_rate_hi=5000,
        apt_rate_lo=3500,  apt_rate_hi=5500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Sriperumbudur is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 602105. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Oragadam": LocalityData(
        city="Chennai", locality="Oragadam",
        land_rate_lo=2800, land_rate_hi=4800,
        apt_rate_lo=3500,  apt_rate_hi=5500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Oragadam is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 602105. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mangadu": LocalityData(
        city="Chennai", locality="Mangadu",
        land_rate_lo=4200, land_rate_hi=6800,
        apt_rate_lo=4500,  apt_rate_hi=6800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Mangadu is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 600122. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kundrathur": LocalityData(
        city="Chennai", locality="Kundrathur",
        land_rate_lo=4000, land_rate_hi=6500,
        apt_rate_lo=4200,  apt_rate_hi=6500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Kundrathur is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 600069. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Madanandapuram": LocalityData(
        city="Chennai", locality="Madanandapuram",
        land_rate_lo=4500, land_rate_hi=7000,
        apt_rate_lo=5000,  apt_rate_hi=7200,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Madanandapuram is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 600125. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thirumudivakkam": LocalityData(
        city="Chennai", locality="Thirumudivakkam",
        land_rate_lo=3800, land_rate_hi=6200,
        apt_rate_lo=4200,  apt_rate_hi=6500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Thirumudivakkam is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 600132. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Irungattukottai": LocalityData(
        city="Chennai", locality="Irungattukottai",
        land_rate_lo=2200, land_rate_hi=4000,
        apt_rate_lo=2800,  apt_rate_hi=4500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Irungattukottai is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 602117. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Walajabad": LocalityData(
        city="Chennai", locality="Walajabad",
        land_rate_lo=800, land_rate_hi=2200,
        apt_rate_lo=1600,  apt_rate_hi=2800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Walajabad is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 631605. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kanchipuram Town": LocalityData(
        city="Chennai", locality="Kanchipuram Town",
        land_rate_lo=1500, land_rate_hi=4000,
        apt_rate_lo=2500,  apt_rate_hi=4500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Kanchipuram Town is a residential locality in Chennai, CMA - Kanchipuram.",
        infra_notes="Pincode 631501. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Vandalur": LocalityData(
        city="Chennai", locality="Vandalur",
        land_rate_lo=3200, land_rate_hi=5200,
        apt_rate_lo=3800,  apt_rate_hi=5800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Vandalur is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 600048. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Urapakkam": LocalityData(
        city="Chennai", locality="Urapakkam",
        land_rate_lo=3500, land_rate_hi=5500,
        apt_rate_lo=3800,  apt_rate_hi=5800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Urapakkam is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603210. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Guduvanchery": LocalityData(
        city="Chennai", locality="Guduvanchery",
        land_rate_lo=3200, land_rate_hi=5200,
        apt_rate_lo=3800,  apt_rate_hi=5800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Guduvanchery is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603202. CMA zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Maraimalai Nagar": LocalityData(
        city="Chennai", locality="Maraimalai Nagar",
        land_rate_lo=1200, land_rate_hi=3000,
        apt_rate_lo=3500,  apt_rate_hi=5500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Maraimalai Nagar is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603209. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Singaperumal Koil": LocalityData(
        city="Chennai", locality="Singaperumal Koil",
        land_rate_lo=1200, land_rate_hi=3000,
        apt_rate_lo=3500,  apt_rate_hi=6200,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Singaperumal Koil is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603204. CMA zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mahindra World City": LocalityData(
        city="Chennai", locality="Mahindra World City",
        land_rate_lo=2000, land_rate_hi=4500,
        apt_rate_lo=5600,  apt_rate_hi=7500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Mahindra World City is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603004. CMA zone.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kattankulathur": LocalityData(
        city="Chennai", locality="Kattankulathur",
        land_rate_lo=2500, land_rate_hi=5000,
        apt_rate_lo=3800,  apt_rate_hi=6000,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Kattankulathur is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603203. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Potheri": LocalityData(
        city="Chennai", locality="Potheri",
        land_rate_lo=3500, land_rate_hi=6000,
        apt_rate_lo=4500,  apt_rate_hi=7000,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Potheri is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603203. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Chengalpattu Town": LocalityData(
        city="Chennai", locality="Chengalpattu Town",
        land_rate_lo=2000, land_rate_hi=4500,
        apt_rate_lo=3000,  apt_rate_hi=5200,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Chengalpattu Town is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603001. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Padappai": LocalityData(
        city="Chennai", locality="Padappai",
        land_rate_lo=1500, land_rate_hi=3500,
        apt_rate_lo=2800,  apt_rate_hi=4800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Padappai is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 601301. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Mambakkam": LocalityData(
        city="Chennai", locality="Mambakkam",
        land_rate_lo=3800, land_rate_hi=6200,
        apt_rate_lo=4500,  apt_rate_hi=6800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Mambakkam is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 600127. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ottiambakkam": LocalityData(
        city="Chennai", locality="Ottiambakkam",
        land_rate_lo=3800, land_rate_hi=6200,
        apt_rate_lo=4500,  apt_rate_hi=6800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Ottiambakkam is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 600130. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Ponmar": LocalityData(
        city="Chennai", locality="Ponmar",
        land_rate_lo=3200, land_rate_hi=5200,
        apt_rate_lo=4000,  apt_rate_hi=6000,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Ponmar is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 600048. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thalambur": LocalityData(
        city="Chennai", locality="Thalambur",
        land_rate_lo=4000, land_rate_hi=5800,
        apt_rate_lo=5800,  apt_rate_hi=8000,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Thalambur is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 600130. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Padur": LocalityData(
        city="Chennai", locality="Padur",
        land_rate_lo=2800, land_rate_hi=4200,
        apt_rate_lo=5500,  apt_rate_hi=7800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Padur is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603103. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kelambakkam": LocalityData(
        city="Chennai", locality="Kelambakkam",
        land_rate_lo=3500, land_rate_hi=5000,
        apt_rate_lo=5000,  apt_rate_hi=7200,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Kelambakkam is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603103. CMA zone.",
        data_confidence=72,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Thiruporur": LocalityData(
        city="Chennai", locality="Thiruporur",
        land_rate_lo=2200, land_rate_hi=4500,
        apt_rate_lo=3500,  apt_rate_hi=5500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Thiruporur is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603110. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Kovalam ECR": LocalityData(
        city="Chennai", locality="Kovalam ECR",
        land_rate_lo=4500, land_rate_hi=9000,
        apt_rate_lo=5000,  apt_rate_hi=8500,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Kovalam ECR is a residential locality in Chennai, CMA - Chengalpattu.",
        infra_notes="Pincode 603112. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Chennai|Arakkonam": LocalityData(
        city="Chennai", locality="Arakkonam",
        land_rate_lo=1200, land_rate_hi=2800,
        apt_rate_lo=2200,  apt_rate_hi=3800,
        guideline_value=0,
        trend_12m="+13.0%",
        micro_context="Arakkonam is a residential locality in Chennai, CMA - Ranipet.",
        infra_notes="Pincode 631001. CMA zone.",
        data_confidence=60,
        demand_drivers=["Residential demand", "Chennai growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),


    # ── Bangalore (unchanged) ───────────────────────────────────────

    "Bangalore|Koramangala": LocalityData(
        city="Bangalore", locality="Koramangala",
        land_rate_lo=53400, land_rate_hi=62600,
        apt_rate_lo=19300,  apt_rate_hi=22700,
        guideline_value=14000,
        trend_12m="+9.8%",
        micro_context="Koramangala is Bangalore's most iconic residential-commercial locality.",
        infra_notes="Forum Mall, 100 Feet Road. No Metro currently.",
        data_confidence=90,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Whitefield": LocalityData(
        city="Bangalore", locality="Whitefield",
        land_rate_lo=26700, land_rate_hi=31300,
        apt_rate_lo=12900,  apt_rate_hi=15100,
        guideline_value=9000,
        trend_12m="+12.2%",
        micro_context="Whitefield is Bangalore's premier IT corridor destination.",
        infra_notes="Whitefield Metro Station (Purple Line). ITPB, Bagmane Tech Park.",
        data_confidence=88,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Indiranagar": LocalityData(
        city="Bangalore", locality="Indiranagar",
        land_rate_lo=57000, land_rate_hi=67000,
        apt_rate_lo=21200,  apt_rate_hi=24800,
        guideline_value=15000,
        trend_12m="+8.4%",
        micro_context="Indiranagar is Bangalore's most lifestyle-driven premium locality.",
        infra_notes="Indiranagar Metro Station. 100 Feet Road.",
        data_confidence=89,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|HSR Layout": LocalityData(
        city="Bangalore", locality="HSR Layout",
        land_rate_lo=36800, land_rate_hi=43200,
        apt_rate_lo=14700,  apt_rate_hi=17300,
        guideline_value=11000,
        trend_12m="+10.9%",
        micro_context="HSR Layout is a meticulously planned locality and second startup hub.",
        infra_notes="ORR frontage. Proposed Metro Phase 3.",
        data_confidence=86,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Marathahalli": LocalityData(
        city="Bangalore", locality="Marathahalli",
        land_rate_lo=22100, land_rate_hi=25900,
        apt_rate_lo=12000,  apt_rate_hi=14000,
        guideline_value=8500,
        trend_12m="+13.5%",
        micro_context="Marathahalli is the highest-appreciating mid-segment locality in Bangalore.",
        infra_notes="Marathahalli Bridge, ORR junction. Proposed Metro.",
        data_confidence=84,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Electronic City": LocalityData(
        city="Bangalore", locality="Electronic City",
        land_rate_lo=15200, land_rate_hi=17800,
        apt_rate_lo=10100,  apt_rate_hi=11900,
        guideline_value=7000,
        trend_12m="+15.0%",
        micro_context="Electronic City is Bangalore's original IT hub — home to Infosys, Wipro, HCL.",
        infra_notes="Electronic City Metro Station (Green Line). Hosur Road NH-44.",
        data_confidence=83,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|JP Nagar": LocalityData(
        city="Bangalore", locality="JP Nagar",
        land_rate_lo=22000, land_rate_hi=26000,
        apt_rate_lo=10500,  apt_rate_hi=13500,
        guideline_value=8000,
        trend_12m="+7.8%",
        micro_context="JP Nagar is a well-established South Bangalore residential locality.",
        infra_notes="NICE Road connectivity. Proposed Metro Phase 3.",
        data_confidence=80,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|BTM Layout": LocalityData(
        city="Bangalore", locality="BTM Layout",
        land_rate_lo=20000, land_rate_hi=24000,
        apt_rate_lo=9500,  apt_rate_hi=12500,
        guideline_value=7500,
        trend_12m="+12.1%",
        micro_context="BTM Layout is a dense, active residential market near Koramangala.",
        infra_notes="ORR access. Silk Board junction nearby.",
        data_confidence=78,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Hebbal": LocalityData(
        city="Bangalore", locality="Hebbal",
        land_rate_lo=24000, land_rate_hi=28000,
        apt_rate_lo=11000,  apt_rate_hi=14000,
        guideline_value=8500,
        trend_12m="+11.3%",
        micro_context="Hebbal is a North Bangalore locality with flyover and lake-front premium.",
        infra_notes="Hebbal flyover. BIAL (airport) road access.",
        data_confidence=80,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Yelahanka": LocalityData(
        city="Bangalore", locality="Yelahanka",
        land_rate_lo=16000, land_rate_hi=20000,
        apt_rate_lo=8500,  apt_rate_hi=11500,
        guideline_value=6500,
        trend_12m="+14.2%",
        micro_context="Yelahanka is a fast-growing North Bangalore suburb near the airport.",
        infra_notes="BIAL Airport: 15km. Proposed Metro extension.",
        data_confidence=76,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Sarjapur Road": LocalityData(
        city="Bangalore", locality="Sarjapur Road",
        land_rate_lo=24000, land_rate_hi=28000,
        apt_rate_lo=11500,  apt_rate_hi=14500,
        guideline_value=9000,
        trend_12m="+12.5%",
        micro_context="Sarjapur Road is a major East Bangalore IT and residential corridor.",
        infra_notes="ORR-Sarjapur junction. Active developer market.",
        data_confidence=82,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

    "Bangalore|Bellandur": LocalityData(
        city="Bangalore", locality="Bellandur",
        land_rate_lo=26000, land_rate_hi=30000,
        apt_rate_lo=12500,  apt_rate_hi=15500,
        guideline_value=9500,
        trend_12m="+12.0%",
        micro_context="Bellandur is a premium East Bangalore locality near Outer Ring Road.",
        infra_notes="ORR access. Bellandur lake (ecological concern).",
        data_confidence=80,
        demand_drivers=["Residential demand", "Bangalore growth"],
        risk_factors=["Verify title and approvals before purchase"],
    ),

}

# ── Lookup helpers ────────────────────────────────────────────────

def get_locality(city: str, locality: str) -> Optional[LocalityData]:
    """Get locality data by city and locality name."""
    key = f"{city}|{locality}"
    data = LOCALITY_DB.get(key)
    if data:
        return data
    city_lower = city.lower()
    loc_lower  = locality.lower()
    for k, v in LOCALITY_DB.items():
        if city_lower in k.lower() and loc_lower in k.lower():
            return v
    return None

def get_confidence_label(score: int) -> str:
    if score >= 85: return "High"
    if score >= 70: return "Good"
    if score >= 55: return "Moderate"
    return "Low"

def list_localities(city: str) -> list[str]:
    """Return all known localities for a city."""
    return [
        v.locality for k, v in LOCALITY_DB.items()
        if v.city.lower() == city.lower()
    ]

from typing import Optional